server:
  port : 8080

spring:
  datasource:
    url:
      jdbc:h2:mem:test
    driverClassName:
      org.h2.Driver
    username:
      sa
    password:
      admin
    platform: h2
  jpa:
    database-platform:
      org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view:
      false
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console:
      settings:
        web-allow-others: false
logging:
  level:
    root: DEBUG